version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: sbadmin
      POSTGRES_PASSWORD: localdevpassword
      POSTGRES_DB: securebank
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]

  backend:
    build: ./backend
    environment:
      PORT: 4000
      NODE_ENV: development
      JWT_SECRET: local-dev-secret-change-me
      DATABASE_URL: postgresql://sbadmin:localdevpassword@db:5432/securebank
    ports: ["4000:4000"]
    depends_on: [db]

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:4000
    ports: ["8080:8080"]
    depends_on: [backend]

volumes:
  dbdata:
